### ISSUE TITLE
Not able to render the local html file which stored into android assets folder

### ISSUE THREAD

**Issue by ap050492** [sunnylqm/react-native-geckoview#1]
Add index.html page location - "../android/app/src/main/assets/HtmlView/index.html"

**Please find sample code in below link**
```
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import GeckoView from 'react-native-geckoview';
const htmlPage = {uri: 'file:///android_asset/HtmlView/index.html'};

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆GeckoView example☆</Text>
        <GeckoView style={{flex: 1}} source={htmlPage} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'stretch',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

**Comment by sunnylqm** [comment]
This project is in a very very early stage, and i've not implemented any feature other than a simple url 😢 
I'll check this when I have time.

**Comment by ap050492** [comment]
> This project is in a very very early stage, and i've not implemented any feature other than a simple url 
> I'll check this when I have time.

No issue @sunnylqm , Appreciate your work

**Comment by ap050492** [comment]
> Add index.html page location - "../android/app/src/main/assets/HtmlView/index.html"
> 
> **Please find sample code in below link**
> 
> ```
> import React, { Component } from 'react';
> import { Platform, StyleSheet, Text, View } from 'react-native';
> import GeckoView from 'react-native-geckoview';
> const htmlPage = {uri: 'file:///android_asset/HtmlView/index.html'};
> 
> export default class App extends Component<{}> {
>   render() {
>     return (
>       <View style={styles.container}>
>         <Text style={styles.welcome}>☆GeckoView example☆</Text>
>         <GeckoView style={{flex: 1}} source={htmlPage} />
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     justifyContent: 'center',
>     alignItems: 'stretch',
>     backgroundColor: '#F5FCFF',
>   },
>   welcome: {
>     fontSize: 20,
>     textAlign: 'center',
>     margin: 10,
>   },
>   instructions: {
>     textAlign: 'center',
>     color: '#333333',
>     marginBottom: 5,
>   },
> });
> ```

I got the solution, Just update the below code in above code
const htmlPage = {uri: 'resource://android/assets/HtmlView/dy.html'};
