### ISSUE TITLE
[No issue] Forked this repo, let me know if you want me to PR anything from there

### ISSUE THREAD

**Issue by filipef101** [sunnylqm/react-native-geckoview#4]
I made a fork of this and added firefox ublock origin extension (or any extension).

I have some stuff in the readme like the aab issue and separate architecture builds to reduce play store download sizes.

**Comment by sunnylqm** [comment]
That's great. Actually I can give you collaborator and npm permission or just transfer to you.

**Comment by filipef101** [comment]
You can add me as collaborator.

Well, this still needs lots of changes, i'll just make PR's if/when I got time, and if someone else wants to contribute I'll specify some:

goBack method: This I tried for a bit but don't much experience with Android libraries for RN and didn't really need it so I made my app without it, if you can give me some pointers or some resource on how to do it would be handy.

load any firefox extension: this shouldn't be hard but probably won't be common usecase

Add a whitelistUrls prop like on rn-webview so we can open some urls outside of the webview

onLoad prop

onError prop

reload method

injectingJavascript should be tricky to do as the way to do it is with a firefox extension

**Comment by sunnylqm** [comment]
Invited. And what's your username for npm?

**Comment by filipef101** [comment]
Filipef101 too

**Comment by sunnylqm** [comment]
Npm permission granted. Have fun with this package!
